### ISSUE TITLE
进展怎么样了

### ISSUE THREAD

**Issue by nosqldb** [heroicyang/nodediscuss#1]
看楼主commit很快，进度怎么样了，最好有个展示页；我在搞一个nosql社区http://nosqldb.org/ ，用的nodeclub，感觉功能不完善，尤其是完善的标签功能缺乏，这块不知道这个版本怎么规划的？

**Comment by heroicyang** [comment]
不好意思，最近家里面出了点事情回了趟家就没时间更新了，今天起继续开始。
恩，近期我会将测试版本部署一个到服务器上。

**Comment by heroicyang** [comment]
好吧，我悄悄的放了一个 `0.1.0` 版本到服务器上了，可以看看初步的成果吧。
http://cnodeclub.heroicyang.com/
PS: 别玩崩了呀...嘿嘿！

**Comment by nosqldb** [comment]
测试了下，感觉标签导航还有优化的余地，这块感觉很重要。

**Comment by heroicyang** [comment]
@nosqldb 标签（节点）只能管理员来创建这点，我是这么认为的：
- 保证其合理性，不出现冗余，一目了然方便检索
- 尽量精简数量，让话题发布者在这些范围内选，是一种规则性的约束
- 如果每个用户都可以自由添加，那就太乱太杂太多了，而且很多人是不太会描述清楚的。当然还有干坏事的人，看看 [AngularJs中文社区](http://angularjs.cn/) 那标签数量，完全没有浏览的雅兴啊

另外，关于发布话题时的下拉选择目前是用的`select`，没有加样式什么的，主要是考虑到兼容移动设备。不过后面会为下拉选择控件加上搜索之类的自定义行为，方便选择。

**Comment by nosqldb** [comment]
这样也有好处，那是否可以指定一个默认节点，或者默认一个上一次话题的节点，这样会加快发布速度。
