### ISSUE TITLE
来支持一下，提点小建议

### ISSUE THREAD

**Issue by tianyisheng** [heroicyang/nodediscuss#3]
刚才使用了一下，非常不错！

提有几个建议哈：
希望能完善一下 wiki，把网站代码的大致架构以及各个模块大概功能稍微写一些（几百字就差不多了），这样其他人更容易上手一起来完善哈。（话说我也想来commit，不知道有哪些是在to-do-list上, 不知道怎么联系您？）

**Comment by heroicyang** [comment]
恩，非常感谢！会在近期完成一份简要的说明，因为我才把一些模块重构了下，`0.1.4` 发布之后就开始着手写文档。

**Comment by heroicyang** [comment]
已经增加了简要的文档：https://github.com/heroicyang/nodediscuss/wiki

关于当前进度：https://github.com/heroicyang/nodediscuss/issues/4
