### ISSUE TITLE
静态资源引用路径是不是有问题

### ISSUE THREAD

**Issue by frontoldman** [heroicyang/nodediscuss#5]
path.join(cwd, config.static.cwd)
这块静态资源的路径貌似有问题，改成上一级目录就对了，还是我配置的不对

**Comment by heroicyang** [comment]
`config` 中 `static.cwd` 是怎样配置的？
另外，现在已经调整配置文件为 `.json` 的了，可以更新下，对配置节点加入了说明文档。
